### PR TITLE
IngestLDD updates per LDD generation

### PR DESCRIPTION
**Pull request by rsjoyner**
## Summary

Enter summary here

## Test Data and/or Report

Enter info here

## Related Issues

Enter related issues here

### CODE REVIEW

**Review by rsjoyner — COMMENTED** [review]
Code review passed validation

**Comment by jordanpadams** [comment]
@rsjoyner LDD generation process failed

**Comment by jordanpadams** [comment]
https://github.com/pds-data-dictionaries/ldd-ladee/actions/runs/8072031503/job/22052961063

not sure what is going on here.

**Comment by jordanpadams** [comment]
@rsjoyner looks like you removed the IngestLDD from the repo:

https://github.com/pds-data-dictionaries/ldd-ladee/tree/rsjoyner-patch-2/src

I think you will want to [add it back from main](https://github.com/pds-data-dictionaries/ldd-ladee/tree/main/src).

Also, make sure you name it `PDS4_LADEE_IngestLDD.xml`. No need to add the dates or anything to the files. It just confuses some of our automation tools

**Pull request merged**
